### ISSUE TITLE
Better document the open group server

### ISSUE THREAD

**Issue by SkewedZeppelin** [oxen-io/session-website#20]
session-pysogs is not mentioned on the website at all or even linked to anywhere.

Please link it on the FAQ page under "What are open groups, and how do they compare with closed groups?".
And maybe write a blurb on it.

**Comment by yougotwill** [comment]
Hey, thanks for the heads up.

We have added a page to our Zendesk https://sessionapp.zendesk.com/hc/en-us/articles/9300270438681-How-do-I-create-an-open-group-using-PySOGS-. Since it's more technical, we won't add it to the FAQ's on getsession.org because it isn't strictly related to the Session app itself.
